name: Python CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      service:
        description: "Select which image to build"
        required: true
        default: "python"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Runs Tests
        run: python py/test_calc.py
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Push the python image to Docker Hub
        if: github.event.inputs.service=="python"
        run: |
          docker build -t ${{secrets.DOCKERHUB_KEY}}/pythonimg:latest ./py
          docker push ${{secrets.DOCKERHUB_KEY}}/pythonimg:latest
      - name: Push the html image to Docker Hub
        if: github.event.inputs.service=="web"
        run: |
          docker build -t ${{secrets.DOCKERHUB_KEY}}/htmlimg:latest ./web
          docker push ${{secrets.DOCKERHUB_KEY}}/htmlimg:latest 